[package]
name = "halloy"
version = "0.1.0"
edition = "2021"

[features]
default = []
debug = ["iced/debug"]

[dependencies]
data = { version = "0.1.0", path = "data" }

chrono = { version = "0.4", features = ['serde'] }
fern = "0.6.1"
iced = { version = "0.9", features = ["tokio", "lazy", "advanced", "image"] }
log = "0.4.16"
once_cell = "1.18"
palette = "=0.7.2"
thiserror = "1.0.30"
tokio = { version = "1.0", features = ["rt", "fs", "process"] }
unicode-segmentation = "1.6"
open = "4.1.0"
image = "0.24.6"

[build-dependencies]
embed-resource = "2.1.1"

[dependencies.uuid]
version = "1.0"
features = ["v4"]

[workspace]
members = ["data"]

[patch.crates-io]
iced = { git = "https://github.com/tarkah/iced", rev = "d79cedd8da99345947f5b9fcb1ebc3a145cc4112" }
iced_core = { git = "https://github.com/tarkah/iced", rev = "d79cedd8da99345947f5b9fcb1ebc3a145cc4112" }
