[package]
name = "halloy"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
data = { version = "0.1.0", path = "data" }

chrono = { version = "0.4", features = ['serde'] }
fern = "0.6.1"
iced = { version = "0.9", features = ["tokio", "lazy", "advanced"] }
log = "0.4.16"
palette = "=0.7.2"
thiserror = "1.0.30"
tokio = { version = "1.0", features = ["rt", "fs", "process"] }
unicode-segmentation = "1.6"
open = "4.1.0"

[dependencies.uuid]
version = "1.0"
features = ["v4"]

[workspace]
members = ["data"]

[patch.crates-io]
iced = { git = "https://github.com/tarkah/iced", rev = "bcd8fda9a6e9c5fb1e1c6d1fa38d807c931bfebc" }
