[package]
name = "halloy"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
data = { version = "0.1.0", path = "data" }
thiserror = "1.0.30"
tokio = { version = "1.0", features = ["rt", "fs", "process"] }
log = "0.4.16"
fern = "0.6.1"
chrono = { version = "0.4", features = ['serde'] }
palette = "=0.7.2"
iced = { git = "https://github.com/iced-rs/iced", rev = "b353767d2d9703aae35f10ebf8a9ee1490c3ae37", features = ["tokio", "lazy", "advanced"] }

[dependencies.uuid]
version = "1.0"
features = ["v4"]

[workspace]
members = ["data"]
