[package]
name = "halloy"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
data = { version = "0.1.0", path = "data" }
thiserror = "1.0.30"
tokio = { version = "1.0", features = ["rt", "fs", "process"] }
log = "0.4.16"
fern = "0.6.1"
chrono = { version = "0.4", features = ['serde'] }
palette = "=0.7.2"
unicode-segmentation = "1.6"
iced = { git = "https://github.com/iced-rs/iced", rev = "60cd864d43be877a5eaee4f5ca32f41b9fb70b79", features = ["tokio", "lazy", "advanced"] }

[dependencies.uuid]
version = "1.0"
features = ["v4"]

[workspace]
members = ["data"]
