# Configuration sample file for Halloy.
# Place this in your user's config directory:
#
# Linux: `$HOME`/.config/halloy
# macOS: `$HOME`/Library/Application Support/halloy
# Windows: `{FOLDERID_RoamingAppData}`\halloy

theme:
  background: "#0A0E14"
  text: "#B3B1AD"
  primary: "#53BDFA"
  secondary: "#91B362"
  error: "#EA6C73"
  warning: "#F9AF4F"
  info: "#FAE994"
  success: "#90E1C6"

# For fields under server, please refer to: https://docs.rs/irc/0.15.0/irc/client/data/config/struct.Config.html#fields

servers:
  - nickname: halloy
    server: irc.libera.chat
    port: 6697
    use_tls: true
    channels:
      - "##rust"