name: "Build and sign for macOS"

on:
  pull_request: #remove this before merge!
  workflow_dispatch:

jobs:
  build:
    name: Build and sign
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build
        run: bash scripts/build-macos.sh

      - name: Sign
        env: 
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CERTIFICATE_NAME: ${{ secrets.MACOS_CERTIFICATE_NAME }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_CI_KEYCHAIN_PWD }}
        run: bash scripts/sign-macos.sh

      - name: Notarize
        env:
          MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
        run: bash scripts/notarize-macos.sh

      - name: Package
        run: bash scripts/package-macos.sh

      - name: Upload dmg
        uses: actions/upload-artifact@v2
        with:
          name: macos-dmg
          path: target/release/macos/halloy.dmg
        
      - name: Upload app
        uses: actions/upload-artifact@v2
        with:
          name: macos-app
          path: target/release/macos/halloy.app